name: DeathChest
version: '${project.version}'
main: net.daechler.deathchest.DeathChest
api-version: 1.20
authors: [Daechler]
description: Protect your items upon your death in a grave.
commands:
  grave:
    description: Teleport to your last grave.
    aliases: [graves, deathchest, chest, death]
    usage: /grave
    permission: deathchest.teleport